apiVersion: metrics.openmcp.cloud/v1beta1
kind: FederatedMetric
metadata:
  labels:
    app.kubernetes.io/name: metrics-operator
    app.kubernetes.io/managed-by: kustomize
  name: federatedmetric-sample
spec:
  # TODO(user): Add fields here
