apiVersion: metrics.cloud.sap/v1beta1
kind: ClusterAccess
metadata:
  labels:
    app.kubernetes.io/name: co-metrics-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusteraccess-sample
spec:
  # TODO(user): Add fields here
