apiVersion: insight.orchestrate.cloud.sap/v1alpha1
kind: Metric
metadata:
  labels:
    app.kubernetes.io/name: metric
    app.kubernetes.io/instance: metric-sample
    app.kubernetes.io/part-of: co-metrics-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: co-metrics-operator
  name: metric-sample
spec:
  # TODO(user): Add fields here
  label: cloud-orchestration
